# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cefbc432552404d84590d94f7ebbf9275e85dc7e8dabcdef2078585ead6af25b777030aa263ec573af2a42596f59d35e49a1dafd815c999369cfc515d3e4124

test:
  secret_key_base: e0a53a970d67d04d6669e83f4a22d3c874766539c60ac6d5248a6920f5f874d6b3aff671003e4cc8c7e31c0c078ce2828b4070d8d6cafebccd2e4c61189f4d7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
